db-host: 192.168.2.18
db-user: admin
db-pass: Czy.190815

server:
  port: 8080

spring:
  application:
    name: circler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db-host}:3306/circler?user=${db-user}&password=${db-pass}&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-test-query: select 1
      connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis:
  mapper-locations: classpath*:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true